//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTTFAQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public int ID { get; set; }
        public string EMAIL { get; set; }
        public string TITLE { get; set; }
        public System.DateTime DATE { get; set; }
        public string CONTENT { get; set; }
    }
}
