//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTTFAQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int ID { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string FULL_NAME { get; set; }
        public string PHONE_NUMBER { get; set; }
        public bool STATUS { get; set; }
        public int CUSTOMER_TYPE { get; set; }
        public int FACULTY_ID { get; set; }
    
        public virtual FACULTY FACULTY { get; set; }
    }
}
