//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTTFAQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_MUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANH_MUC()
        {
            this.CAU_HOI = new HashSet<CAU_HOI>();
        }
    
        public int ID { get; set; }
        public string DANH_MUC1 { get; set; }
        public string MO_TA { get; set; }
        public string HINH_ANH { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public int ID_TAI_KHOAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAU_HOI> CAU_HOI { get; set; }
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
    }
}
