//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTTFAQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUOT_TIM_TU_KHOA
    {
        public int ID { get; set; }
        public string TU_KHOA { get; set; }
        public int LUOT_TIM { get; set; }
    }
}
