//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTTFAQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION
    {
        public int ID { get; set; }
        public string QUESTION_CODE { get; set; }
        public string QUESTION_NAME { get; set; }
        public int CATEGORY_ID { get; set; }
        public string CONTENT { get; set; }
        public string IMAGE_URL { get; set; }
        public bool STATUS { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
