//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTTFAQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYEN_CUA_USER
    {
        public int ID { get; set; }
        public int ID_TAI_KHOAN { get; set; }
        public int ID_QUYEN { get; set; }
    
        public virtual QUYEN QUYEN { get; set; }
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
    }
}
