//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTTFAQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLIDER
    {
        public int ID { get; set; }
        public string IMAGE_URL { get; set; }
        public string TEXT { get; set; }
        public Nullable<int> ORDER { get; set; }
        public Nullable<bool> IS_VISIBLE { get; set; }
    }
}
