//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNTTFAQ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAI_KHOAN
    {
        public string ID { get; set; }
        public string MAT_KHAU { get; set; }
        public string EMAIL { get; set; }
        public string MA_SO_NGUOI_DUNG { get; set; }
        public string FULL_NAM { get; set; }
    }
}
