USE [master]
GO
/****** Object:  Database [DIEUBANTHUONGHOIWEBSITE]    Script Date: 6/29/2021 10:06:25 PM ******/
CREATE DATABASE [DIEUBANTHUONGHOIWEBSITE]
GO
USE [DIEUBANTHUONGHOIWEBSITE]
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET ARITHABORT OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET  MULTI_USER 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET QUERY_STORE = OFF
GO
USE [DIEUBANTHUONGHOIWEBSITE]
GO
/****** Object:  Table [dbo].[CAU_HOI]    Script Date: 6/29/2021 10:06:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAU_HOI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CAU_HOI] [nvarchar](max) NOT NULL,
	[MO_TA] [nvarchar](max) NULL,
	[NGAY_TAO] [datetime2](7) NULL,
	[ID_DANH_MUC] [int] NOT NULL,
	[ID_TAI_KHOAN] [int] NOT NULL,
	[LUOT_XEM] [int] NOT NULL,
	[DUYET_DANG] [bit] NULL,
 CONSTRAINT [PK__CAU_HOI__3214EC2754BC25F3] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CAU_TRA_LOI]    Script Date: 6/29/2021 10:06:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAU_TRA_LOI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_CAU_HOI] [int] NOT NULL,
	[CAU_TRA_LOI] [nvarchar](max) NULL,
	[NGAY_TRA_LOI] [datetime2](7) NULL,
	[ID_TAI_KHOAN] [int] NOT NULL,
 CONSTRAINT [PK__CAU_TRA___3214EC276510EEDA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DANH_MUC]    Script Date: 6/29/2021 10:06:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DANH_MUC](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DANH_MUC] [nvarchar](50) NOT NULL,
	[MO_TA] [nvarchar](max) NULL,
	[HINH_ANH] [nvarchar](max) NOT NULL,
	[NGAY_TAO] [datetime2](7) NULL,
	[ID_TAI_KHOAN] [int] NOT NULL,
 CONSTRAINT [PK__DANH_MUC__3214EC2797265295] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LICH_SU_CHINH_SUA_CAU_HOI]    Script Date: 6/29/2021 10:06:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LICH_SU_CHINH_SUA_CAU_HOI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CAU_HOI_TRUOC_CHINH_SUA] [nvarchar](max) NOT NULL,
	[MO_TA_TRUOC_CHINH_SUA] [nvarchar](max) NULL,
	[NGAY_CHINH_SUA] [datetime2](7) NULL,
	[ID_DANH_MUC_TRUOC_CHINH_SUA] [int] NOT NULL,
	[CAU_HOI_SAU_CHINH_SUA] [nvarchar](max) NOT NULL,
	[MO_TA_SAU_CHINH_SUA] [nvarchar](max) NULL,
	[ID_DANH_MUC_SAU_CHINH_SUA] [int] NOT NULL,
	[ID_TAI_KHOAN] [int] NOT NULL,
 CONSTRAINT [PK__LICH_SU___3214EC27154974E5] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LICH_SU_CHINH_SUA_DANH_MUC]    Script Date: 6/29/2021 10:06:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LICH_SU_CHINH_SUA_DANH_MUC](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DANH_MUC_TRUOC_CHINH_SUA] [nvarchar](max) NOT NULL,
	[MO_TA_TRUOC_CHINH_SUA] [nvarchar](max) NULL,
	[NGAY_CHINH_SUA] [datetime2](7) NULL,
	[HINH_ANH_TRUOC_CHINH_SUA] [nvarchar](max) NOT NULL,
	[DANH_MUC_SAU_CHINH_SUA] [nvarchar](max) NOT NULL,
	[MO_TA_SAU_CHINH_SUA] [nvarchar](max) NULL,
	[HINH_ANH_SAU_CHINH_SUA] [nvarchar](max) NOT NULL,
	[ID_TAI_KHOAN] [int] NOT NULL,
 CONSTRAINT [PK__LICH_SU___3214EC275B06760C] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LUOT_TIM_TU_KHOA]    Script Date: 6/29/2021 10:06:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LUOT_TIM_TU_KHOA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TU_KHOA] [nvarchar](max) NULL,
	[LUOT_TIM] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[QUYEN]    Script Date: 6/29/2021 10:06:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QUYEN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TEN_QUYEN] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[QUYEN_CUA_USER]    Script Date: 6/29/2021 10:06:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QUYEN_CUA_USER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_TAI_KHOAN] [int] NOT NULL,
	[ID_QUYEN] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAI_KHOAN]    Script Date: 6/29/2021 10:06:26 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAI_KHOAN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AVATAR] [nvarchar](max) NOT NULL,
	[MAT_KHAU] [varchar](50) NULL,
	[EMAIL] [varchar](max) NOT NULL,
	[MA_SO_NGUOI_DUNG] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[CAU_HOI] ON 
GO
INSERT [dbo].[CAU_HOI] ([ID], [CAU_HOI], [MO_TA], [NGAY_TAO], [ID_DANH_MUC], [ID_TAI_KHOAN], [LUOT_XEM], [DUYET_DANG]) VALUES (30, N'test', N'1', CAST(N'2021-02-10T00:00:00.0000000' AS DateTime2), 3, 2, 3, 0)
GO
INSERT [dbo].[CAU_HOI] ([ID], [CAU_HOI], [MO_TA], [NGAY_TAO], [ID_DANH_MUC], [ID_TAI_KHOAN], [LUOT_XEM], [DUYET_DANG]) VALUES (31, N'tesst', N'1', NULL, 3, 2, 3, 0)
GO
INSERT [dbo].[CAU_HOI] ([ID], [CAU_HOI], [MO_TA], [NGAY_TAO], [ID_DANH_MUC], [ID_TAI_KHOAN], [LUOT_XEM], [DUYET_DANG]) VALUES (32, N'test', N'1', NULL, 3, 2, 3, 0)
GO
INSERT [dbo].[CAU_HOI] ([ID], [CAU_HOI], [MO_TA], [NGAY_TAO], [ID_DANH_MUC], [ID_TAI_KHOAN], [LUOT_XEM], [DUYET_DANG]) VALUES (33, N'12', N'21', CAST(N'2021-06-29T17:44:26.3729745' AS DateTime2), 7, 2, 0, 0)
GO
INSERT [dbo].[CAU_HOI] ([ID], [CAU_HOI], [MO_TA], [NGAY_TAO], [ID_DANH_MUC], [ID_TAI_KHOAN], [LUOT_XEM], [DUYET_DANG]) VALUES (34, N'ngay thang nam', N'123', CAST(N'2021-06-29T17:45:23.7777825' AS DateTime2), 7, 2, 0, 0)
GO
SET IDENTITY_INSERT [dbo].[CAU_HOI] OFF
GO
SET IDENTITY_INSERT [dbo].[DANH_MUC] ON 
GO
INSERT [dbo].[DANH_MUC] ([ID], [DANH_MUC], [MO_TA], [HINH_ANH], [NGAY_TAO], [ID_TAI_KHOAN]) VALUES (3, N'Công tác sinh viên', N'Những vấn đề mà sinh hay gặp phải', N'Hình ảnh', CAST(N'2021-06-29T13:06:41.3033333' AS DateTime2), 2)
GO
INSERT [dbo].[DANH_MUC] ([ID], [DANH_MUC], [MO_TA], [HINH_ANH], [NGAY_TAO], [ID_TAI_KHOAN]) VALUES (5, N'Công tác đào tạo', N'Những vấn đề liên quan đến quá trình học tập', N'Hình ảnh', CAST(N'2021-06-29T13:08:31.5900000' AS DateTime2), 2)
GO
INSERT [dbo].[DANH_MUC] ([ID], [DANH_MUC], [MO_TA], [HINH_ANH], [NGAY_TAO], [ID_TAI_KHOAN]) VALUES (7, N'Câu hỏi khác', N'Những vấn đề khác', N'Hình ảnh', CAST(N'2021-06-29T13:09:29.7033333' AS DateTime2), 2)
GO
SET IDENTITY_INSERT [dbo].[DANH_MUC] OFF
GO
SET IDENTITY_INSERT [dbo].[TAI_KHOAN] ON 
GO
INSERT [dbo].[TAI_KHOAN] ([ID], [AVATAR], [MAT_KHAU], [EMAIL], [MA_SO_NGUOI_DUNG]) VALUES (2, N'Hình ảnh', NULL, N'thanh187pm13902@vanlanguni.vn', N'187pm13902')
GO
SET IDENTITY_INSERT [dbo].[TAI_KHOAN] OFF
GO
ALTER TABLE [dbo].[CAU_HOI] ADD  CONSTRAINT [DF_LUOT_XEM]  DEFAULT ((0)) FOR [LUOT_XEM]
GO
ALTER TABLE [dbo].[CAU_HOI] ADD  CONSTRAINT [DF_CAU_HOI_DUYET_DANG]  DEFAULT ((0)) FOR [DUYET_DANG]
GO
ALTER TABLE [dbo].[LUOT_TIM_TU_KHOA] ADD  CONSTRAINT [DF_LUOT_TIM_TU_KHOA]  DEFAULT ((1)) FOR [LUOT_TIM]
GO
ALTER TABLE [dbo].[CAU_HOI]  WITH CHECK ADD  CONSTRAINT [FK_CAU_HOI_DANH_MUC] FOREIGN KEY([ID_DANH_MUC])
REFERENCES [dbo].[DANH_MUC] ([ID])
GO
ALTER TABLE [dbo].[CAU_HOI] CHECK CONSTRAINT [FK_CAU_HOI_DANH_MUC]
GO
ALTER TABLE [dbo].[CAU_HOI]  WITH CHECK ADD  CONSTRAINT [FK_CAU_HOI_TAI_KHOAN] FOREIGN KEY([ID_TAI_KHOAN])
REFERENCES [dbo].[TAI_KHOAN] ([ID])
GO
ALTER TABLE [dbo].[CAU_HOI] CHECK CONSTRAINT [FK_CAU_HOI_TAI_KHOAN]
GO
ALTER TABLE [dbo].[CAU_TRA_LOI]  WITH CHECK ADD  CONSTRAINT [FK_CAU_TRA_LOI_CAU_HOI] FOREIGN KEY([ID_CAU_HOI])
REFERENCES [dbo].[CAU_HOI] ([ID])
GO
ALTER TABLE [dbo].[CAU_TRA_LOI] CHECK CONSTRAINT [FK_CAU_TRA_LOI_CAU_HOI]
GO
ALTER TABLE [dbo].[CAU_TRA_LOI]  WITH CHECK ADD  CONSTRAINT [FK_CAU_TRA_LOI_TAI_KHOAN] FOREIGN KEY([ID_TAI_KHOAN])
REFERENCES [dbo].[TAI_KHOAN] ([ID])
GO
ALTER TABLE [dbo].[CAU_TRA_LOI] CHECK CONSTRAINT [FK_CAU_TRA_LOI_TAI_KHOAN]
GO
ALTER TABLE [dbo].[DANH_MUC]  WITH CHECK ADD  CONSTRAINT [FK_DANH_MUC_TAI_KHOAN] FOREIGN KEY([ID_TAI_KHOAN])
REFERENCES [dbo].[TAI_KHOAN] ([ID])
GO
ALTER TABLE [dbo].[DANH_MUC] CHECK CONSTRAINT [FK_DANH_MUC_TAI_KHOAN]
GO
ALTER TABLE [dbo].[LICH_SU_CHINH_SUA_CAU_HOI]  WITH CHECK ADD  CONSTRAINT [FK_LICH_SU_CHINH_SUA_CAU_HOI_TAI_KHOAN] FOREIGN KEY([ID_TAI_KHOAN])
REFERENCES [dbo].[TAI_KHOAN] ([ID])
GO
ALTER TABLE [dbo].[LICH_SU_CHINH_SUA_CAU_HOI] CHECK CONSTRAINT [FK_LICH_SU_CHINH_SUA_CAU_HOI_TAI_KHOAN]
GO
ALTER TABLE [dbo].[LICH_SU_CHINH_SUA_DANH_MUC]  WITH CHECK ADD  CONSTRAINT [FK_LICH_SU_CHINH_SUA_DANH_MUC_TAI_KHOAN] FOREIGN KEY([ID_TAI_KHOAN])
REFERENCES [dbo].[TAI_KHOAN] ([ID])
GO
ALTER TABLE [dbo].[LICH_SU_CHINH_SUA_DANH_MUC] CHECK CONSTRAINT [FK_LICH_SU_CHINH_SUA_DANH_MUC_TAI_KHOAN]
GO
ALTER TABLE [dbo].[QUYEN_CUA_USER]  WITH CHECK ADD  CONSTRAINT [FK_QUYEN_CUA_USER_QUYEN] FOREIGN KEY([ID_QUYEN])
REFERENCES [dbo].[QUYEN] ([ID])
GO
ALTER TABLE [dbo].[QUYEN_CUA_USER] CHECK CONSTRAINT [FK_QUYEN_CUA_USER_QUYEN]
GO
ALTER TABLE [dbo].[QUYEN_CUA_USER]  WITH CHECK ADD  CONSTRAINT [FK_QUYEN_CUA_USER_TAI_KHOAN] FOREIGN KEY([ID_TAI_KHOAN])
REFERENCES [dbo].[TAI_KHOAN] ([ID])
GO
ALTER TABLE [dbo].[QUYEN_CUA_USER] CHECK CONSTRAINT [FK_QUYEN_CUA_USER_TAI_KHOAN]
GO
USE [master]
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET  READ_WRITE 
GO
