USE [master]
GO
/****** Object:  Database [DIEUBANTHUONGHOIWEBSITE]    Script Date: 6/27/2021 9:55:32 PM ******/
CREATE DATABASE [DIEUBANTHUONGHOIWEBSITE]
-- CONTAINMENT = NONE
-- ON  PRIMARY 
--( NAME = N'DIEUBANTHUONGHOIWEBSITE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\DIEUBANTHUONGHOIWEBSITE.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
-- LOG ON 
--( NAME = N'DIEUBANTHUONGHOIWEBSITE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\DIEUBANTHUONGHOIWEBSITE_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
--GO
--ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET COMPATIBILITY_LEVEL = 120
--GO
--IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
--begin
--EXEC [DIEUBANTHUONGHOIWEBSITE].[dbo].[sp_fulltext_database] @action = 'enable'
--end
--GO
USE [DIEUBANTHUONGHOIWEBSITE]
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET ARITHABORT OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET  MULTI_USER 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET DELAYED_DURABILITY = DISABLED 
GO
USE [DIEUBANTHUONGHOIWEBSITE]
GO
/****** Object:  Table [dbo].[CAU_HOI]    Script Date: 6/27/2021 9:55:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAU_HOI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TEN_CAU_HOI] [nvarchar](max) NOT NULL,
	[MO_TA] [nvarchar](max) NULL,
	[NGAY_TAO] [datetime] NOT NULL,
	[ID_DANH_MUC] [int] NOT NULL,
	[NGUOI_DANG] [int] NOT NULL,
	[LUOT_XEM] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CAU_TRA_LOI]    Script Date: 6/27/2021 9:55:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAU_TRA_LOI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_CAU_HOI] [int] NOT NULL,
	[CAU_TRA_LOI] [nvarchar](max) NULL,
	[NGAY_TRA_LOI] [datetime] NOT NULL,
	[NGUOI_TRA_LOI] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DANH_MUC]    Script Date: 6/27/2021 9:55:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DANH_MUC](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TEN_DANH_MUC] [nvarchar](50) NOT NULL,
	[MO_TA] [nvarchar](max) NULL,
	[HINH_ANH] [nvarchar](max) NOT NULL,
	[NGAY_TAO] [datetime] NOT NULL,
	[NGUOI_TAO] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LICH_SU_CHINH_SUA_CAU_HOI]    Script Date: 6/27/2021 9:55:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LICH_SU_CHINH_SUA_CAU_HOI](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TEN_CAU_HOI_TRUOC_CHINH_SUA] [nvarchar](max) NOT NULL,
	[MO_TA_TRUOC_CHINH_SUA] [nvarchar](max) NULL,
	[NGAY_CHINH_SUA] [datetime] NOT NULL,
	[ID_DANH_MUC_TRUOC_CHINH_SUA] [int] NOT NULL,
	[TEN_CAU_HOI_SAU_CHINH_SUA] [nvarchar](max) NOT NULL,
	[MO_TA_SAU_CHINH_SUA] [nvarchar](max) NULL,
	[ID_DANH_MUC_SAU_CHINH_SUA] [int] NOT NULL,
	[NGUOI_CHINH_SUA] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LICH_SU_CHINH_SUA_DANH_MUC]    Script Date: 6/27/2021 9:55:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LICH_SU_CHINH_SUA_DANH_MUC](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TEN_DANH_MUC_TRUOC_CHINH_SUA] [nvarchar](max) NOT NULL,
	[MO_TA_TRUOC_CHINH_SUA] [nvarchar](max) NULL,
	[NGAY_CHINH_SUA] [datetime] NOT NULL,
	[HINH_ANH_TRUOC_CHINH_SUA] [nvarchar](max) NOT NULL,
	[TEN_DANH_MUC_SAU_CHINH_SUA] [nvarchar](max) NOT NULL,
	[MO_TA_SAU_CHINH_SUA] [nvarchar](max) NULL,
	[HINH_ANH_SAU_CHINH_SUA] [nvarchar](max) NOT NULL,
	[NGUOI_CHINH_SUA] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LUOT_TIM_TU_KHOA]    Script Date: 6/27/2021 9:55:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LUOT_TIM_TU_KHOA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TU_KHOA] [nvarchar](max) NULL,
	[LUOT_TIM] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[QUYEN]    Script Date: 6/27/2021 9:55:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QUYEN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TEN_QUYEN] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[QUYEN_CUA_USER]    Script Date: 6/27/2021 9:55:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QUYEN_CUA_USER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_NGUOI_DUNG] [int] NOT NULL,
	[ID_QUYEN] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAI_KHOAN]    Script Date: 6/27/2021 9:55:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAI_KHOAN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AVATAR] [nvarchar](max) NOT NULL,
	[MAT_KHAU] [varchar](50) NULL,
	[EMAIL] [varchar](max) NOT NULL,
	[MA_SO] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object: CONSTRAINT   ******/
ALTER TABLE [dbo].[CAU_HOI] ADD  DEFAULT (getdate()) FOR [NGAY_TAO]
GO
ALTER TABLE [dbo].[CAU_HOI] ADD  CONSTRAINT [DF_LUOT_XEM]  DEFAULT ((0)) FOR [LUOT_XEM]
GO
ALTER TABLE [dbo].[CAU_TRA_LOI] ADD  DEFAULT (getdate()) FOR [NGAY_TRA_LOI]
GO
ALTER TABLE [dbo].[DANH_MUC] ADD  DEFAULT (getdate()) FOR [NGAY_TAO]
GO
ALTER TABLE [dbo].[LICH_SU_CHINH_SUA_CAU_HOI] ADD  DEFAULT (getdate()) FOR [NGAY_CHINH_SUA]
GO
ALTER TABLE [dbo].[LICH_SU_CHINH_SUA_DANH_MUC] ADD  DEFAULT (getdate()) FOR [NGAY_CHINH_SUA]
GO
ALTER TABLE [dbo].[LUOT_TIM_TU_KHOA] ADD  CONSTRAINT [DF_LUOT_TIM_TU_KHOA]  DEFAULT ((1)) FOR [LUOT_TIM]
GO
ALTER TABLE [dbo].[CAU_HOI]  WITH CHECK ADD  CONSTRAINT [FK_CAU_HOI_DANH_MUC] FOREIGN KEY([ID_DANH_MUC])
REFERENCES [dbo].[DANH_MUC] ([ID])
GO
ALTER TABLE [dbo].[CAU_HOI] CHECK CONSTRAINT [FK_CAU_HOI_DANH_MUC]
GO
ALTER TABLE [dbo].[CAU_HOI]  WITH CHECK ADD  CONSTRAINT [FK_CAU_HOI_TAI_KHOAN] FOREIGN KEY([NGUOI_DANG])
REFERENCES [dbo].[TAI_KHOAN] ([ID])
GO
ALTER TABLE [dbo].[CAU_HOI] CHECK CONSTRAINT [FK_CAU_HOI_TAI_KHOAN]
GO
ALTER TABLE [dbo].[CAU_TRA_LOI]  WITH CHECK ADD  CONSTRAINT [FK_CAU_TRA_LOI_CAU_HOI] FOREIGN KEY([ID_CAU_HOI])
REFERENCES [dbo].[CAU_HOI] ([ID])
GO
ALTER TABLE [dbo].[CAU_TRA_LOI] CHECK CONSTRAINT [FK_CAU_TRA_LOI_CAU_HOI]
GO
ALTER TABLE [dbo].[CAU_TRA_LOI]  WITH CHECK ADD  CONSTRAINT [FK_CAU_TRA_LOI_TAI_KHOAN] FOREIGN KEY([NGUOI_TRA_LOI])
REFERENCES [dbo].[TAI_KHOAN] ([ID])
GO
ALTER TABLE [dbo].[CAU_TRA_LOI] CHECK CONSTRAINT [FK_CAU_TRA_LOI_TAI_KHOAN]
GO
ALTER TABLE [dbo].[DANH_MUC]  WITH CHECK ADD  CONSTRAINT [FK_DANH_MUC_TAI_KHOAN] FOREIGN KEY([NGUOI_TAO])
REFERENCES [dbo].[TAI_KHOAN] ([ID])
GO
ALTER TABLE [dbo].[DANH_MUC] CHECK CONSTRAINT [FK_DANH_MUC_TAI_KHOAN]
GO
ALTER TABLE [dbo].[LICH_SU_CHINH_SUA_CAU_HOI]  WITH CHECK ADD  CONSTRAINT [FK_LICH_SU_CHINH_SUA_CAU_HOI_TAI_KHOAN] FOREIGN KEY([NGUOI_CHINH_SUA])
REFERENCES [dbo].[TAI_KHOAN] ([ID])
GO
ALTER TABLE [dbo].[LICH_SU_CHINH_SUA_CAU_HOI] CHECK CONSTRAINT [FK_LICH_SU_CHINH_SUA_CAU_HOI_TAI_KHOAN]
GO
ALTER TABLE [dbo].[LICH_SU_CHINH_SUA_DANH_MUC]  WITH CHECK ADD  CONSTRAINT [FK_LICH_SU_CHINH_SUA_DANH_MUC_TAI_KHOAN] FOREIGN KEY([NGUOI_CHINH_SUA])
REFERENCES [dbo].[TAI_KHOAN] ([ID])
GO
ALTER TABLE [dbo].[LICH_SU_CHINH_SUA_DANH_MUC] CHECK CONSTRAINT [FK_LICH_SU_CHINH_SUA_DANH_MUC_TAI_KHOAN]
GO
ALTER TABLE [dbo].[QUYEN_CUA_USER]  WITH CHECK ADD  CONSTRAINT [FK_QUYEN_CUA_USER_QUYEN] FOREIGN KEY([ID_QUYEN])
REFERENCES [dbo].[QUYEN] ([ID])
GO
ALTER TABLE [dbo].[QUYEN_CUA_USER] CHECK CONSTRAINT [FK_QUYEN_CUA_USER_QUYEN]
GO
ALTER TABLE [dbo].[QUYEN_CUA_USER]  WITH CHECK ADD  CONSTRAINT [FK_QUYEN_CUA_USER_TAI_KHOAN] FOREIGN KEY([ID_NGUOI_DUNG])
REFERENCES [dbo].[TAI_KHOAN] ([ID])
GO
ALTER TABLE [dbo].[QUYEN_CUA_USER] CHECK CONSTRAINT [FK_QUYEN_CUA_USER_TAI_KHOAN]
GO
USE [master]
GO
ALTER DATABASE [DIEUBANTHUONGHOIWEBSITE] SET  READ_WRITE 
GO
